-- 建表脚本-DB2
-- 数据源表
CREATE TABLE IND_DATASOURCE(
  ID  VARCHAR(32) NOT NULL,
  DATASOURCE_NAME  VARCHAR(50),
  DATASOURCE_TYPE  VARCHAR(32),
  DATASOURCE_SCHEMA  VARCHAR(50),
  DATASOURCE_DRIVER  VARCHAR(100),
  DATASOURCE_URL  VARCHAR(200),
  DATASOURCE_USER  VARCHAR(50),
  DATASOURCE_PASSWORD  VARCHAR(100),
  DATASOURCE_DESC  VARCHAR(100),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_DATASOURCE PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_DATASOURCE IS '应用层-数据源表';
 COMMENT ON IND_DATASOURCE(
ID IS  '数据源ID',
DATASOURCE_NAME IS  '数据源名称',
DATASOURCE_TYPE IS  '数据库类型',
DATASOURCE_SCHEMA IS  '数据库SCHEMA',
DATASOURCE_DRIVER IS  '数据库驱动',
DATASOURCE_URL IS  '连接URL',
DATASOURCE_USER IS  '用户名',
DATASOURCE_PASSWORD IS  '密码',
DATASOURCE_DESC IS  '描述',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;
-- 指标分类表
CREATE TABLE IND_CATEGORY(
  ID  VARCHAR(32) NOT NULL,
  CATEGORY_TYPE  VARCHAR(5),
  CATEGORY_NAME  VARCHAR(100),
  CATEGORY_DESC  VARCHAR(255),
  PARENT_ID  VARCHAR(32),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_CATEGORY PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_CATEGORY IS '应用层-指标分类表';
 COMMENT ON IND_CATEGORY(
ID IS  '分类ID',
CATEGORY_TYPE IS  '分类模块',
CATEGORY_NAME IS  '分类名称',
CATEGORY_DESC IS  '分类描述',
PARENT_ID IS  '父节点',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 指标参数表
CREATE TABLE IND_PARAMETER(
  ID  VARCHAR(32) NOT NULL,
  CATEGORY_ID  VARCHAR(32),
  PARM_CODE  VARCHAR(32),
  PARM_NAME  VARCHAR(256),
  PARM_TYPE  VARCHAR(20),
  PARM_VALUE  VARCHAR(256),
  PARM_DESC  VARCHAR(512),
  STATUS  VARCHAR(5),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_PARAMETER PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_PARAMETER IS '应用层-指标参数表';
 COMMENT ON IND_PARAMETER(
ID IS  '参数ID',
CATEGORY_ID IS  '参数类型',
PARM_CODE IS  '参数编号',
PARM_NAME IS  '参数名称',
PARM_TYPE IS  '参数值类型',
PARM_VALUE IS  '参数值',
PARM_DESC IS  '参数描述',
STATUS IS  '状态(1-启用，0-停用)',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 维度定义表
CREATE TABLE IND_DIMENSION(
  ID  VARCHAR(32) NOT NULL,
  DIM_CODE  VARCHAR(32),
  DATASOURCE_ID  VARCHAR(32),
  DIM_NAME  VARCHAR(5),
  TABLE_NAME  VARCHAR(100),
  NAME_COLUMN  VARCHAR(512),
  NAME_COLUMN_DESC  VARCHAR(512),
  CODE_COLUMN  VARCHAR(32),
  CODE_COLUMN_DESC  VARCHAR(32),
  PID  VARCHAR(32),
  LEVEL  VARCHAR(5),
  ALIAS  VARCHAR(32),
  PK_FLAG  VARCHAR(5),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_DIMENSION PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_DIMENSION IS '应用层-维度定义表';
 COMMENT ON IND_DIMENSION(
ID IS  '维度ID',
DIM_CODE IS  '维度编号',
DATASOURCE_ID IS  '数据源ID(预留)',
DIM_NAME IS  '维度名称',
TABLE_NAME IS  '维表表名称',
NAME_COLUMN IS  '维度显示字段(可多字段逗号隔开)',
NAME_COLUMN_DESC IS  '维度显示字段描述(可多字段逗号隔开)',
CODE_COLUMN IS  '代码字段(用户管理指标对象)',
CODE_COLUMN_DESC IS  '代码字段描述',
PID IS  '父ID(预留)',
LEVEL IS  '级别(预留)',
ALIAS IS  '别名',
PK_FLAG IS  '主键标志',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 指标基本信息表
CREATE TABLE IND_INDICATOR_INFO(
  ID  VARCHAR(32) NOT NULL,
  IE_CODE  VARCHAR(32) NOT NULL,
  IE_NAME  VARCHAR(100),
  CATEGORY_ID  VARCHAR(32),
  IE_PROP  VARCHAR(5),
  IE_TYPE  VARCHAR(5),
  IE_DESC  VARCHAR(255),
  IE_RULE  VARCHAR(512),
  IE_DEFAULT_VALUE  DECIMAL(24,6),
  IE_METHOD  VARCHAR(5),
  CALC_FREQ  VARCHAR(5),
  STATUS  VARCHAR(5),
  IE_DATA_UNIT  VARCHAR(5),
  IE_LEVEL  DECIMAL(5),
  START_DATE  DATE,
  END_DATE  DATE,
  RETENTION  VARCHAR(32),
  PROCESS_INSTANCE_ID  VARCHAR(32),
  MANAGE_DEPT  VARCHAR(32),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_INDICATOR_INFO PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_INDICATOR_INFO IS '应用层-指标基本信息表';
 COMMENT ON IND_INDICATOR_INFO(
ID IS  '指标ID',
IE_CODE IS  '指标编号',
IE_NAME IS  '指标名称',
CATEGORY_ID IS  '指标分类ID(树状)',
IE_PROP IS  '指标类别(1-财务类，2-经营类...)',
IE_TYPE IS  '指标类型(0-手工指标，1-基础指标，2-衍生指标，3-定性指标)',
IE_DESC IS  '指标描述',
IE_RULE IS  '指标业务规则',
IE_DEFAULT_VALUE IS  '默认值',
IE_METHOD IS  '取值方式( 衍生指标时：1-四则运算，2-复杂SQL，3-限制，4-EXCEL公式)',
CALC_FREQ IS  '计算频度(D-天，M-月，Q-季度，Y-年)',
STATUS IS  '指标状态（0-已创建，1-已提交，2-已审批）',
IE_DATA_UNIT IS  '指标单位(1-元，2-分，3-个……)',
IE_LEVEL IS  '指标层级(根据依赖关系确定层级，基础指标为0)',
START_DATE IS  '生效日期',
END_DATE IS  '失效日期',
RETENTION IS  '结果保留期限（1,Y）',
PROCESS_INSTANCE_ID IS  '审核流程ID',
MANAGE_DEPT IS  '管理部门(解释部门)',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 基础指标计算规则表
CREATE TABLE IND_BASE_RULE(
  ID  VARCHAR(32) NOT NULL,
  IE_CODE  VARCHAR(32),
  STATUS  VARCHAR(5),
  DATA_SOURCE  VARCHAR(32),
  EXPRESSION  VARCHAR(100),
  DATA_TABLE  VARCHAR(60),
  PERIOD_CODE  VARCHAR(60),
  RULE_DESC  VARCHAR(512),
  ANALYSABLE  VARCHAR(5),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_BASE_RULE PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_BASE_RULE IS '应用层-基础指标规则表';
 COMMENT ON IND_BASE_RULE(
ID IS  '规则ID',
IE_CODE IS  '指标编号',
STATUS IS  '状态(1-启用，0-禁用)',
DATA_SOURCE IS  '数据源(默认本库)',
EXPRESSION IS  '取数表达式',
DATA_TABLE IS  '取数表名',
PERIOD_CODE IS  '考核期/数据日期(对应的后台字段)',
RULE_DESC IS  '规则说明',
ANALYSABLE IS  '是否可分析',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;
-- 基础指标附加规则表
CREATE TABLE IND_BASE_RULE_FILTER(
  ID  VARCHAR(32) NOT NULL,
  IE_CODE  VARCHAR(32),
  EXP_SEQ  DECIMAL(5),
  EXP_PREFIX  VARCHAR(50),
  EXP_NAME  VARCHAR(100),
  EXP_SYMBOL  VARCHAR(20),
  EXP_VALUE  VARCHAR(300),
  EXP_POSTFIX  VARCHAR(50),
  EXP_VALUE_DESC  VARCHAR(255),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_BASE_RULE_FILTER PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_BASE_RULE_FILTER IS '应用层-基础指标附加规则表';
 COMMENT ON IND_BASE_RULE_FILTER(
ID IS  '指标规则ID',
IE_CODE IS  '指标编号',
EXP_SEQ IS  '表达式序号',
EXP_PREFIX IS  '表达式前缀',
EXP_NAME IS  '表达式名称',
EXP_SYMBOL IS  '运算符',
EXP_VALUE IS  '表达式值',
EXP_POSTFIX IS  '表达式后缀',
EXP_VALUE_DESC IS  '表达式值描述',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 指标维度关系表
CREATE TABLE IND_DIM_RELATION(
  ID  VARCHAR(32) NOT NULL,
  RULE_ID  VARCHAR(32),
  IE_CODE  VARCHAR(32),
  DIM_CODE  DECIMAL(5),
  IS_MAIN  VARCHAR(5),
  TABLE_COLUMN  VARCHAR(50),
  DIM_COLUMN  VARCHAR(50),
  REMARK  VARCHAR(255),
  DIM_SEQ  DECIMAL(5),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_DIM_RELATION PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_DIM_RELATION IS '应用层-指标维度关系表';
 COMMENT ON IND_DIM_RELATION(
ID IS  '关系ID',
RULE_ID IS  '规则ID',
IE_CODE IS  '指标编号',
DIM_CODE IS  '维度编号',
IS_MAIN IS  '主维度(分析指标用)',
TABLE_COLUMN IS  '数据表字段',
DIM_COLUMN IS  '维度对应字段',
REMARK IS  '备注',
DIM_SEQ IS  '序号',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 衍生指标计算规则表
CREATE TABLE IND_DERIVE_RULE(
  ID  VARCHAR(32) NOT NULL,
  IE_CODE  VARCHAR(32),
  STATUS  VARCHAR(5),
  RULE_TYPE  VARCHAR(60),
  CALC_RULE  VARCHAR(1000),
  RULE_DESC  VARCHAR(1000),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_DERIVE_RULE PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_DERIVE_RULE IS '应用层-衍生指标计算规则表';
 COMMENT ON IND_DERIVE_RULE(
ID IS  '规则ID',
IE_CODE IS  '指标编号',
STATUS IS  '状态(1-启用，0-禁用)',
RULE_TYPE IS  '规则类型(1-四则运算，2-SQL公式，3-限制，4-EXCEL公式)',
CALC_RULE IS  '计算规则(四则公式/SQL公式/EXCEL公式)',
RULE_DESC IS  '规则说明',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;
-- 衍生指标依赖关系表
CREATE TABLE IND_DERIVE_RULE_DEPENDENCE(
  ID  VARCHAR(32) NOT NULL,
  RULE_ID  VARCHAR(32),
  IE_CODE  VARCHAR(32),
  DEPEND_TYPE  VARCHAR(5),
  DEPEND_CODE  VARCHAR(32),
  DATA_FLAG  VARCHAR(5),
  VALUE_FLAG  VARCHAR(5),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_DERIVE_RULE_DEPENDENCE PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_DERIVE_RULE_DEPENDENCE IS '应用层-衍生指标依赖关系表';
 COMMENT ON IND_DERIVE_RULE_DEPENDENCE(
ID IS  '依赖ID',
RULE_ID IS  '规则ID',
IE_CODE IS  '指标编号',
DEPEND_TYPE IS  '依赖指标类型(1-基础，2-衍生指标，3-参数)',
DEPEND_CODE IS  '依赖指标编号',
DATA_FLAG IS  '数据标志（备用，0-自身，1-父级，9-全辖）',
VALUE_FLAG IS  '值标志(0-指标值,1-计划值，2-调整值，3-原始值)',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;
-- 指标补录表
CREATE TABLE IND_INDICATOR_MANUAL(
  ID  VARCHAR(32) NOT NULL,
  IE_CODE  VARCHAR(32),
  IE_NAME  VARCHAR(100),
  IE_TYPE  VARCHAR(5),
  IE_VALUE  DECIMAL,
  IE_PLAN_VALUE  DECIMAL,
  PERIOD_CODE  VARCHAR(32),
  OBJECT_CODE  VARCHAR(32),
  OBJECT_TYPE  VARCHAR(5),
  STATUS  VARCHAR(5),
  PROCESS_INSTANCE_ID  VARCHAR(32),
  RETENTION  VARCHAR(32),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_INDICATOR_MANUAL PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_INDICATOR_MANUAL IS '应用层-指标补录表';
 COMMENT ON IND_INDICATOR_MANUAL(
ID IS  '补录ID',
IE_CODE IS  '指标编号',
IE_NAME IS  '指标名称',
IE_TYPE IS  '指标类型',
IE_VALUE IS  '指标结果',
IE_PLAN_VALUE IS  '指标计划值',
PERIOD_CODE IS  '计算周期',
OBJECT_CODE IS  '对象编号',
OBJECT_TYPE IS  '对象类别(维度ID)',
STATUS IS  '状态',
PROCESS_INSTANCE_ID IS  '审核流程ID',
RETENTION IS  '结果保留期限（1,Y）',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;
-- 指标结果表
CREATE TABLE IND_INDICATOR_RESULT(
  ID  VARCHAR(32) NOT NULL,
  IE_ID  VARCHAR(32),
  IE_CODE  VARCHAR(32),
  IE_NAME  VARCHAR(100),
  IE_TYPE  VARCHAR(5),
  IE_RULE  VARCHAR(512),
  IE_VALUE  DECIMAL,
  IE_ADJUST_VALUE  DECIMAL,
  IE_PLAN_VALUE  DECIMAL,
  PERIOD_CODE  VARCHAR(32),
  OBJECT_CODE  VARCHAR(32),
  OBJECT_TYPE  VARCHAR(5),
  STATUS  VARCHAR(5),
  PROCESS_INSTANCE_ID  VARCHAR(32),
  RETENTION  VARCHAR(32),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT IND_INDICATOR_RESULT PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE IND_INDICATOR_RESULT IS '应用层-指标结果表';
 COMMENT ON IND_INDICATOR_RESULT(
ID IS  '结果ID',
IE_ID IS  '指标ID',
IE_CODE IS  '指标编号',
IE_NAME IS  '指标名称',
IE_TYPE IS  '指标类型',
IE_RULE IS  '指标规则(备查)',
IE_VALUE IS  '指标计算结果',
IE_ADJUST_VALUE IS  '指标手工调整结果',
IE_PLAN_VALUE IS  '指标计划值',
PERIOD_CODE IS  '计算周期',
OBJECT_CODE IS  '对象编号',
OBJECT_TYPE IS  '对象类别(维度ID)',
STATUS IS  '状态',
PROCESS_INSTANCE_ID IS  '审核流程ID',
RETENTION IS  '结果保留期限（1,Y）',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;

