-- 建表脚本-DB2
-- 应用管理表
CREATE TABLE MNT_APP(
  ID  VARCHAR(32) NOT NULL,
  NAME  VARCHAR(255),
  UPLOAD_PATH  VARCHAR(255),
  DEPLOY_PATH  VARCHAR(255),
  BACKUP_PATH  VARCHAR(255),
  PORT  DECIMAL(10,0),
  START_SCRIPT  VARCHAR(4000),
  DEPLOY_SCRIPT  VARCHAR(4000),
  CREATE_TIME  TIMESTAMP,
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT MNT_APP PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE MNT_APP IS '应用层-应用管理表';
 COMMENT ON MNT_APP(
ID IS  '应用ID',
NAME IS  '应用名称',
UPLOAD_PATH IS  '上传目录',
DEPLOY_PATH IS  '部署路径',
BACKUP_PATH IS  '备份路径',
PORT IS  '应用端口',
START_SCRIPT IS  '启动脚本',
DEPLOY_SCRIPT IS  '部署脚本',
CREATE_TIME IS  '创建日期',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 数据库管理表
CREATE TABLE MNT_DATABASE(
  ID  VARCHAR(32) NOT NULL,
  NAME  VARCHAR(255),
  JDBC_URL  VARCHAR(255),
  USER_NAME  VARCHAR(32),
  PWD  VARCHAR(255),
  CREATE_TIME  TIMESTAMP,
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT MNT_DATABASE PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE MNT_DATABASE IS '应用层-数据库管理表';
 COMMENT ON MNT_DATABASE(
ID IS  '编号',
NAME IS  '名称',
JDBC_URL IS  'jdbc连接',
USER_NAME IS  '账号',
PWD IS  '密码',
CREATE_TIME IS  '',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 部署管理表
CREATE TABLE MNT_DEPLOY(
  ID  VARCHAR(32) NOT NULL,
  APP_ID  VARCHAR(32),
  CREATE_TIME  TIMESTAMP,
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT MNT_DEPLOY PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE MNT_DEPLOY IS '应用层-部署管理表';
 COMMENT ON MNT_DEPLOY(
ID IS  '编号',
APP_ID IS  '应用编号',
CREATE_TIME IS  '创建时间',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 部署历史表
CREATE TABLE MNT_DEPLOY_HISTORY(
  ID  VARCHAR(32) NOT NULL,
  APP_NAME  VARCHAR(255),
  DEPLOY_DATE  TIMESTAMP,
  DEPLOY_USER  VARCHAR(32),
  IP  VARCHAR(20),
  DEPLOY_ID  VARCHAR(32),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT MNT_DEPLOY_HISTORY PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE MNT_DEPLOY_HISTORY IS '应用层-部署历史表';
 COMMENT ON MNT_DEPLOY_HISTORY(
ID IS  '编号',
APP_NAME IS  '应用名称',
DEPLOY_DATE IS  '部署日期',
DEPLOY_USER IS  '部署用户',
IP IS  '服务器IP',
DEPLOY_ID IS  '部署编号',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;
-- 服务器管理表
CREATE TABLE MNT_SERVER(
  ID  VARCHAR(32) NOT NULL,
  ACCOUNT  VARCHAR(255),
  IP  VARCHAR(255),
  NAME  VARCHAR(255),
  PASSWORD  VARCHAR(255),
  PORT  DECIMAL(10,0),
  CREATE_TIME  TIMESTAMP,
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT MNT_SERVER PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE MNT_SERVER IS '应用层-服务器管理表';
 COMMENT ON MNT_SERVER(
ID IS  'IP地址',
ACCOUNT IS  '账号',
IP IS  'IP地址',
NAME IS  '名称',
PASSWORD IS  '密码',
PORT IS  '端口',
CREATE_TIME IS  '',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期',
TENANT IS  '租户'
);
COMMIT;
-- 应用与服务器关联表
CREATE TABLE MNT_DEPLOY_SERVER(
  ID  VARCHAR(32) NOT NULL,
  DEPLOY_ID  VARCHAR(32),
  SERVER_ID  VARCHAR(32),
  CRT_USER_CODE  VARCHAR(32),
  CRT_ORG_CODE  VARCHAR(32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR(32),
  UPD_ORG_CODE  VARCHAR(32),
  UPD_DATE  TIMESTAMP,
  TENANT  VARCHAR(32),
CONSTRAINT MNT_DEPLOY_SERVER PRIMARY KEY (ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE MNT_DEPLOY_SERVER IS '应用层-应用与服务器关联表';
 COMMENT ON MNT_DEPLOY_SERVER(
ID IS  '依赖ID',
DEPLOY_ID IS  '部署ID',
SERVER_ID IS  '服务器ID',
CRT_USER_CODE IS  '创建用户',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建时间',
UPD_USER_CODE IS  '修改用户',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改时间',
TENANT IS  '租户'
);
COMMIT;

