-- 建表脚本-Oracle
-- 应用管理表
CREATE TABLE MNT_APP(
  ID  VARCHAR2(32) NOT NULL,
  NAME  VARCHAR2(255),
  UPLOAD_PATH  VARCHAR2(255),
  DEPLOY_PATH  VARCHAR2(255),
  BACKUP_PATH  VARCHAR2(255),
  PORT  DECIMAL(10,0),
  START_SCRIPT  VARCHAR2(4000),
  DEPLOY_SCRIPT  VARCHAR2(4000),
  CREATE_TIME  DATE,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT MNT_APP PRIMARY KEY (ID)
);
 COMMENT ON TABLE MNT_APP IS '应用层-应用管理表';
 COMMENT ON COLUMN MNT_APP.ID IS  '应用ID';
COMMENT ON COLUMN MNT_APP.NAME IS  '应用名称';
COMMENT ON COLUMN MNT_APP.UPLOAD_PATH IS  '上传目录';
COMMENT ON COLUMN MNT_APP.DEPLOY_PATH IS  '部署路径';
COMMENT ON COLUMN MNT_APP.BACKUP_PATH IS  '备份路径';
COMMENT ON COLUMN MNT_APP.PORT IS  '应用端口';
COMMENT ON COLUMN MNT_APP.START_SCRIPT IS  '启动脚本';
COMMENT ON COLUMN MNT_APP.DEPLOY_SCRIPT IS  '部署脚本';
COMMENT ON COLUMN MNT_APP.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN MNT_APP.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN MNT_APP.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN MNT_APP.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN MNT_APP.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN MNT_APP.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN MNT_APP.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN MNT_APP.TENANT IS  '租户';

-- 数据库管理表
CREATE TABLE MNT_DATABASE(
  ID  VARCHAR2(32) NOT NULL,
  NAME  VARCHAR2(255),
  JDBC_URL  VARCHAR2(255),
  USER_NAME  VARCHAR2(32),
  PWD  VARCHAR2(255),
  CREATE_TIME  DATE,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT MNT_DATABASE PRIMARY KEY (ID)
);
 COMMENT ON TABLE MNT_DATABASE IS '应用层-数据库管理表';
 COMMENT ON COLUMN MNT_DATABASE.ID IS  '编号';
COMMENT ON COLUMN MNT_DATABASE.NAME IS  '名称';
COMMENT ON COLUMN MNT_DATABASE.JDBC_URL IS  'jdbc连接';
COMMENT ON COLUMN MNT_DATABASE.USER_NAME IS  '账号';
COMMENT ON COLUMN MNT_DATABASE.PWD IS  '密码';
COMMENT ON COLUMN MNT_DATABASE.CREATE_TIME IS  '';
COMMENT ON COLUMN MNT_DATABASE.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN MNT_DATABASE.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN MNT_DATABASE.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN MNT_DATABASE.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN MNT_DATABASE.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN MNT_DATABASE.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN MNT_DATABASE.TENANT IS  '租户';

-- 部署管理表
CREATE TABLE MNT_DEPLOY(
  ID  VARCHAR2(32) NOT NULL,
  APP_ID  VARCHAR2(32),
  CREATE_TIME  DATE,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT MNT_DEPLOY PRIMARY KEY (ID)
);
 COMMENT ON TABLE MNT_DEPLOY IS '应用层-部署管理表';
 COMMENT ON COLUMN MNT_DEPLOY.ID IS  '编号';
COMMENT ON COLUMN MNT_DEPLOY.APP_ID IS  '应用编号';
COMMENT ON COLUMN MNT_DEPLOY.CREATE_TIME IS  '创建时间';
COMMENT ON COLUMN MNT_DEPLOY.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN MNT_DEPLOY.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN MNT_DEPLOY.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN MNT_DEPLOY.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN MNT_DEPLOY.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN MNT_DEPLOY.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN MNT_DEPLOY.TENANT IS  '租户';

-- 部署历史表
CREATE TABLE MNT_DEPLOY_HISTORY(
  ID  VARCHAR2(32) NOT NULL,
  APP_NAME  VARCHAR2(255),
  DEPLOY_DATE  DATE,
  DEPLOY_USER  VARCHAR2(32),
  IP  VARCHAR2(20),
  DEPLOY_ID  VARCHAR2(32),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT MNT_DEPLOY_HISTORY PRIMARY KEY (ID)
);
 COMMENT ON TABLE MNT_DEPLOY_HISTORY IS '应用层-部署历史表';
 COMMENT ON COLUMN MNT_DEPLOY_HISTORY.ID IS  '编号';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.APP_NAME IS  '应用名称';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.DEPLOY_DATE IS  '部署日期';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.DEPLOY_USER IS  '部署用户';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.IP IS  '服务器IP';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.DEPLOY_ID IS  '部署编号';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN MNT_DEPLOY_HISTORY.TENANT IS  '租户';

-- 服务器管理表
CREATE TABLE MNT_SERVER(
  ID  VARCHAR2(32) NOT NULL,
  ACCOUNT  VARCHAR2(255),
  IP  VARCHAR2(255),
  NAME  VARCHAR2(255),
  PASSWORD  VARCHAR2(255),
  PORT  DECIMAL(10,0),
  CREATE_TIME  DATE,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT MNT_SERVER PRIMARY KEY (ID)
);
 COMMENT ON TABLE MNT_SERVER IS '应用层-服务器管理表';
 COMMENT ON COLUMN MNT_SERVER.ID IS  'IP地址';
COMMENT ON COLUMN MNT_SERVER.ACCOUNT IS  '账号';
COMMENT ON COLUMN MNT_SERVER.IP IS  'IP地址';
COMMENT ON COLUMN MNT_SERVER.NAME IS  '名称';
COMMENT ON COLUMN MNT_SERVER.PASSWORD IS  '密码';
COMMENT ON COLUMN MNT_SERVER.PORT IS  '端口';
COMMENT ON COLUMN MNT_SERVER.CREATE_TIME IS  '';
COMMENT ON COLUMN MNT_SERVER.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN MNT_SERVER.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN MNT_SERVER.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN MNT_SERVER.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN MNT_SERVER.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN MNT_SERVER.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN MNT_SERVER.TENANT IS  '租户';

-- 应用与服务器关联表
CREATE TABLE MNT_DEPLOY_SERVER(
  ID  VARCHAR2(32) NOT NULL,
  DEPLOY_ID  VARCHAR2(32),
  SERVER_ID  VARCHAR2(32),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT MNT_DEPLOY_SERVER PRIMARY KEY (ID)
);
 COMMENT ON TABLE MNT_DEPLOY_SERVER IS '应用层-应用与服务器关联表';
 COMMENT ON COLUMN MNT_DEPLOY_SERVER.ID IS  '依赖ID';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.DEPLOY_ID IS  '部署ID';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.SERVER_ID IS  '服务器ID';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN MNT_DEPLOY_SERVER.TENANT IS  '租户';


