-- 建表脚本-Mysql
-- 应用管理表
CREATE TABLE MNT_APP(
ID  VARCHAR(32) NOT NULL  COMMENT '应用ID',
NAME  VARCHAR(255) COMMENT '应用名称',
UPLOAD_PATH  VARCHAR(255) COMMENT '上传目录',
DEPLOY_PATH  VARCHAR(255) COMMENT '部署路径',
BACKUP_PATH  VARCHAR(255) COMMENT '备份路径',
PORT  DECIMAL(10,0) COMMENT '应用端口',
START_SCRIPT  VARCHAR(4000) COMMENT '启动脚本',
DEPLOY_SCRIPT  VARCHAR(4000) COMMENT '部署脚本',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-应用管理表';

-- 数据库管理表
CREATE TABLE MNT_DATABASE(
ID  VARCHAR(32) NOT NULL  COMMENT '编号',
NAME  VARCHAR(255) COMMENT '名称',
JDBC_URL  VARCHAR(255) COMMENT 'jdbc连接',
USER_NAME  VARCHAR(32) COMMENT '账号',
PWD  VARCHAR(255) COMMENT '密码',
CREATE_TIME  TIMESTAMP COMMENT '',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-数据库管理表';

-- 部署管理表
CREATE TABLE MNT_DEPLOY(
ID  VARCHAR(32) NOT NULL  COMMENT '编号',
APP_ID  VARCHAR(32) COMMENT '应用编号',
CREATE_TIME  TIMESTAMP COMMENT '创建时间',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-部署管理表';

-- 部署历史表
CREATE TABLE MNT_DEPLOY_HISTORY(
ID  VARCHAR(32) NOT NULL  COMMENT '编号',
APP_NAME  VARCHAR(255) COMMENT '应用名称',
DEPLOY_DATE  TIMESTAMP COMMENT '部署日期',
DEPLOY_USER  VARCHAR(32) COMMENT '部署用户',
IP  VARCHAR(20) COMMENT '服务器IP',
DEPLOY_ID  VARCHAR(32) COMMENT '部署编号',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-部署历史表';

-- 服务器管理表
CREATE TABLE MNT_SERVER(
ID  VARCHAR(32) NOT NULL  COMMENT 'IP地址',
ACCOUNT  VARCHAR(255) COMMENT '账号',
IP  VARCHAR(255) COMMENT 'IP地址',
NAME  VARCHAR(255) COMMENT '名称',
PASSWORD  VARCHAR(255) COMMENT '密码',
PORT  DECIMAL(10,0) COMMENT '端口',
CREATE_TIME  TIMESTAMP COMMENT '',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-服务器管理表';

-- 应用与服务器关联表
CREATE TABLE MNT_DEPLOY_SERVER(
ID  VARCHAR(32) NOT NULL  COMMENT '依赖ID',
DEPLOY_ID  VARCHAR(32) COMMENT '部署ID',
SERVER_ID  VARCHAR(32) COMMENT '服务器ID',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-应用与服务器关联表';


