-- 建表脚本-Mysql
-- 系统用户表
CREATE TABLE SYS_USER(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
AVATAR  VARCHAR(32) COMMENT '头像',
EMAIL  VARCHAR(255) COMMENT '邮箱',
ENABLED  CHAR(1) COMMENT '状态：1启用、0禁用',
PASSWORD  VARCHAR(255) COMMENT '密码',
USERNAME  VARCHAR(255) COMMENT '用户名',
DEPT_ID  VARCHAR(32) COMMENT '部门名称',
PHONE  VARCHAR(255) COMMENT '手机号码',
JOB_ID  VARCHAR(32) COMMENT '岗位名称',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
LAST_PASSWORD_RESET_TIME  TIMESTAMP COMMENT '最后修改密码的日期',
NICK_NAME  VARCHAR(255) COMMENT '',
SEX  VARCHAR(255) COMMENT '',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-系统用户表';

-- 部门信息表
CREATE TABLE SYS_DEPT(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
NAME  VARCHAR(255) COMMENT '名称',
PID  VARCHAR(32) COMMENT '上级部门',
ENABLED  CHAR(1) COMMENT '状态',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-部门信息表';

-- 角色表
CREATE TABLE SYS_ROLE(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
NAME  VARCHAR(255) COMMENT '名称',
REMARK  VARCHAR(255) COMMENT '备注',
DATA_SCOPE  VARCHAR(255) COMMENT '数据权限',
ROLE_LEVEL  DECIMAL(10,0) COMMENT '角色级别',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
PERMISSION  VARCHAR(255) COMMENT '功能权限',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-角色表';

-- 用户角色关联表
CREATE TABLE SYS_USER_ROLE(
ID  VARCHAR(32) NOT NULL  COMMENT '主键ID',
USER_ID  VARCHAR(32) COMMENT '用户ID',
ROLE_ID  VARCHAR(32) COMMENT '角色ID',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-用户角色关联表';

-- 角色部门关联表
CREATE TABLE SYS_ROLE_DEPT(
ID  VARCHAR(32) NOT NULL  COMMENT '依赖ID',
ROLE_ID  VARCHAR(32) NOT NULL  COMMENT '角色ID',
DEPT_ID  VARCHAR(32) NOT NULL  COMMENT '部门ID',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-角色部门关联表';

-- 系统菜单表
CREATE TABLE SYS_MENU(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
I_FRAME  CHAR(1) COMMENT '是否外链',
NAME  VARCHAR(255) COMMENT '菜单名称',
COMPONENT  VARCHAR(255) COMMENT '组件',
PID  VARCHAR(32) COMMENT '上级菜单ID',
SORT  DECIMAL(19,0) COMMENT '排序',
ICON  VARCHAR(255) COMMENT '图标',
PATH  VARCHAR(255) COMMENT '链接地址',
CACHE  CHAR(1) COMMENT '缓存',
HIDDEN  CHAR(1) COMMENT '隐藏',
COMPONENT_NAME  VARCHAR(20) COMMENT '组件名称',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
PERMISSION  VARCHAR(20) COMMENT '权限',
TYPE  DECIMAL(10,0) COMMENT '类型',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-系统菜单表';

-- 对象菜单关联表
CREATE TABLE SYS_OBJECT_MENU(
ID  VARCHAR(32) NOT NULL  COMMENT '结果ID',
OBJECT_TYPE  VARCHAR(32) COMMENT '类型（dept-部门，role-角色，user-用户）',
OBJECT_ID  VARCHAR(32) COMMENT '对象ID',
MENU_ID  VARCHAR(32) COMMENT '菜单ID',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-对象菜单关联表';

-- 数据字典表
CREATE TABLE SYS_DICT(
ID  VARCHAR(32) NOT NULL  COMMENT '主键ID',
DICT_NAME  VARCHAR(100) COMMENT '字典名称',
NAME  VARCHAR(32) COMMENT '字典名称',
DICT_CODE  VARCHAR(100) COMMENT '字典编码',
REMARK  VARCHAR(255) COMMENT '描述',
DESCRIPTION  VARCHAR(255) COMMENT '描述',
DEL_FLAG  INT(1) COMMENT '删除状态',
CREATE_BY  VARCHAR(32) COMMENT '创建人',
CREATE_TIME  TIMESTAMPTIME COMMENT '创建时间',
UPDATE_BY  VARCHAR(32) COMMENT '更新人',
UPDATE_TIME  TIMESTAMPTIME COMMENT '更新时间',
TYPE  INT(1) COMMENT '字典类型0为string,1为number',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-数据字典表';

-- 数据字典详情表
CREATE TABLE SYS_DICT_DETAIL(
ID  VARCHAR(32) NOT NULL  COMMENT '主键ID',
LABEL  VARCHAR(255) COMMENT '字典标签',
VALUE  VARCHAR(255) COMMENT '字典值',
SORT  VARCHAR(5) COMMENT '排序',
DICT_ID  VARCHAR(32) COMMENT '字典id',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-数据字典详情表';

-- 岗位表
CREATE TABLE SYS_JOB(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
NAME  VARCHAR(255) COMMENT '岗位名称',
ENABLED  CHAR(1) COMMENT '岗位状态',
SORT  DECIMAL(19,0) COMMENT '岗位排序',
DEPT_ID  VARCHAR(32) COMMENT '部门ID',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-岗位表';

-- 系统日志表
CREATE TABLE SYS_LOG(
ID  VARCHAR(32) NOT NULL  COMMENT '主键ID',
CREATE_TIME  TIMESTAMP COMMENT '时间',
DESCRIPTION  VARCHAR(255) COMMENT '描述',
EXCEPTION_DETAIL  TEXT COMMENT '异常',
LOG_TYPE  VARCHAR(255) COMMENT '类型',
METHOD  VARCHAR(255) COMMENT '方法',
PARAMS  TEXT COMMENT '参数',
REQUEST_IP  VARCHAR(255) COMMENT 'IP',
TIME  DECIMAL(19,0) COMMENT '耗时',
USERNAME  VARCHAR(255) COMMENT '用户',
ADDRESS  VARCHAR(255) COMMENT '地址',
BROWSER  VARCHAR(255) COMMENT '浏览器',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-系统日志表';

-- 角色菜单关联表
CREATE TABLE SYS_ROLE_MENU(
ID  VARCHAR(32) NOT NULL  COMMENT '主键ID',
MENU_ID  VARCHAR(32) COMMENT '菜单ID',
ROLE_ID  VARCHAR(32) COMMENT '角色ID',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-角色菜单关联表';

-- 访客记录表
CREATE TABLE SYS_VISITS(
ID  VARCHAR(32) NOT NULL  COMMENT '主键',
CREATE_TIME  TIMESTAMP COMMENT '创建时间',
VISITS_DATE  VARCHAR(255) COMMENT '访问时间',
IP_COUNTS  DECIMAL(19,0) COMMENT 'IP数',
PV_COUNTS  DECIMAL(19,0) COMMENT 'PV数',
WEEK_DAY  VARCHAR(255) COMMENT '周次',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-访客记录';

-- 代码生成器配置表
CREATE TABLE SYS_GEN_CONFIG(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
TABLE_NAME  VARCHAR(255) COMMENT '表名',
AUTHOR  VARCHAR(255) COMMENT '作者',
COVER  CHAR(1) COMMENT '是否覆盖',
MODULE_NAME  VARCHAR(255) COMMENT '模块名称',
PACK  VARCHAR(255) COMMENT '至于哪个包下',
PATH  VARCHAR(255) COMMENT '前端代码生成的路径',
API_PATH  VARCHAR(255) COMMENT '前端Api文件路径',
PREFIX  VARCHAR(255) COMMENT '表前缀',
API_ALIAS  VARCHAR(255) COMMENT '接口名称',
REMARK  VARCHAR(255) COMMENT '表描述',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-代码生成器配置表';

-- 代码生成字段信息存储表
CREATE TABLE SYS_GEN_COLUMN_CONFIG(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
TABLE_NAME  VARCHAR(255) COMMENT '表名',
COLUMN_NAME  VARCHAR(255) COMMENT '列名',
COLUMN_TYPE  VARCHAR(255) COMMENT '列类型',
DICT_NAME  VARCHAR(255) COMMENT '字典名',
EXTRA  VARCHAR(255) COMMENT '',
FORM_SHOW  CHAR(1) COMMENT '',
FORM_TYPE  VARCHAR(255) COMMENT '',
KEY_TYPE  VARCHAR(255) COMMENT '',
LIST_SHOW  CHAR(1) COMMENT '',
NOT_NULL  CHAR(1) COMMENT '',
QUERY_TYPE  VARCHAR(255) COMMENT '查询类型',
REMARK  VARCHAR(255) COMMENT '备注',
DATE_ANNOTATION  VARCHAR(255) COMMENT '',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-代码生成字段信息存储表';

-- 定时任务表
CREATE TABLE SYS_QUARTZ_JOB(
ID  VARCHAR(32) NOT NULL  COMMENT 'ID',
BEAN_NAME  VARCHAR(255) COMMENT 'Spring Bean名称',
CRON_EXPRESSION  VARCHAR(255) COMMENT 'cron 表达式',
IS_PAUSE  CHAR(1) COMMENT '状态：1暂停、0启用',
JOB_NAME  VARCHAR(255) COMMENT '任务名称',
METHOD_NAME  VARCHAR(255) COMMENT '方法名称',
PARAMS  VARCHAR(255) COMMENT '参数',
REMARK  VARCHAR(255) COMMENT '备注',
CREATE_TIME  TIMESTAMP COMMENT '创建日期',
DATE_ANNOTATION  VARCHAR(255) COMMENT '',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-定时任务表';

-- 定时任务日志表
CREATE TABLE SYS_QUARTZ_LOG(
ID  VARCHAR(32) NOT NULL  COMMENT '',
BAEN_NAME  VARCHAR(255) COMMENT '',
CREATE_TIME  TIMESTAMP COMMENT '',
CRON_EXPRESSION  VARCHAR(255) COMMENT '',
EXCEPTION_DETAIL  TEXT COMMENT '',
IS_SUCCESS  CHAR(1) COMMENT '',
JOB_NAME  VARCHAR(255) COMMENT '',
METHOD_NAME  VARCHAR(255) COMMENT '',
PARAMS  VARCHAR(255) COMMENT '',
TIME  DECIMAL(19,0) COMMENT '',
CRT_USER_CODE  VARCHAR(32) COMMENT '创建用户',
CRT_ORG_CODE  VARCHAR(32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建时间',
UPD_USER_CODE  VARCHAR(32) COMMENT '修改用户',
UPD_ORG_CODE  VARCHAR(32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改时间',
TENANT  VARCHAR(32) COMMENT '租户',
 PRIMARY KEY (ID)
)
 COMMENT = '应用层-定时任务日志表';


