-- 建表脚本-Oracle
-- 系统用户表
CREATE TABLE SYS_USER(
  ID  VARCHAR2(32) NOT NULL,
  AVATAR  VARCHAR2(32),
  EMAIL  VARCHAR2(255),
  ENABLED  CHAR(1),
  PASSWORD  VARCHAR2(255),
  USERNAME  VARCHAR2(255),
  DEPT_ID  VARCHAR2(32),
  PHONE  VARCHAR2(255),
  JOB_ID  VARCHAR2(32),
  CREATE_TIME  DATE,
  LAST_PASSWORD_RESET_TIME  DATE,
  NICK_NAME  VARCHAR2(255),
  SEX  VARCHAR2(255),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_USER PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_USER IS '应用层-系统用户表';
 COMMENT ON COLUMN SYS_USER.ID IS  'ID';
COMMENT ON COLUMN SYS_USER.AVATAR IS  '头像';
COMMENT ON COLUMN SYS_USER.EMAIL IS  '邮箱';
COMMENT ON COLUMN SYS_USER.ENABLED IS  '状态：1启用、0禁用';
COMMENT ON COLUMN SYS_USER.PASSWORD IS  '密码';
COMMENT ON COLUMN SYS_USER.USERNAME IS  '用户名';
COMMENT ON COLUMN SYS_USER.DEPT_ID IS  '部门名称';
COMMENT ON COLUMN SYS_USER.PHONE IS  '手机号码';
COMMENT ON COLUMN SYS_USER.JOB_ID IS  '岗位名称';
COMMENT ON COLUMN SYS_USER.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN SYS_USER.LAST_PASSWORD_RESET_TIME IS  '最后修改密码的日期';
COMMENT ON COLUMN SYS_USER.NICK_NAME IS  '';
COMMENT ON COLUMN SYS_USER.SEX IS  '';
COMMENT ON COLUMN SYS_USER.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN SYS_USER.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_USER.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN SYS_USER.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN SYS_USER.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_USER.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN SYS_USER.TENANT IS  '租户';

-- 部门信息表
CREATE TABLE SYS_DEPT(
  ID  VARCHAR2(32) NOT NULL,
  NAME  VARCHAR2(255),
  PID  VARCHAR2(32),
  ENABLED  CHAR(1),
  CREATE_TIME  DATE,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_DEPT PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_DEPT IS '应用层-部门信息表';
 COMMENT ON COLUMN SYS_DEPT.ID IS  'ID';
COMMENT ON COLUMN SYS_DEPT.NAME IS  '名称';
COMMENT ON COLUMN SYS_DEPT.PID IS  '上级部门';
COMMENT ON COLUMN SYS_DEPT.ENABLED IS  '状态';
COMMENT ON COLUMN SYS_DEPT.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN SYS_DEPT.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN SYS_DEPT.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_DEPT.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN SYS_DEPT.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN SYS_DEPT.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_DEPT.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN SYS_DEPT.TENANT IS  '租户';

-- 角色表
CREATE TABLE SYS_ROLE(
  ID  VARCHAR2(32) NOT NULL,
  NAME  VARCHAR2(255),
  REMARK  VARCHAR2(255),
  DATA_SCOPE  VARCHAR2(255),
  ROLE_LEVEL  DECIMAL(10,0),
  CREATE_TIME  DATE,
  PERMISSION  VARCHAR2(255),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_ROLE PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_ROLE IS '应用层-角色表';
 COMMENT ON COLUMN SYS_ROLE.ID IS  'ID';
COMMENT ON COLUMN SYS_ROLE.NAME IS  '名称';
COMMENT ON COLUMN SYS_ROLE.REMARK IS  '备注';
COMMENT ON COLUMN SYS_ROLE.DATA_SCOPE IS  '数据权限';
COMMENT ON COLUMN SYS_ROLE.ROLE_LEVEL IS  '角色级别';
COMMENT ON COLUMN SYS_ROLE.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN SYS_ROLE.PERMISSION IS  '功能权限';
COMMENT ON COLUMN SYS_ROLE.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN SYS_ROLE.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_ROLE.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN SYS_ROLE.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN SYS_ROLE.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_ROLE.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN SYS_ROLE.TENANT IS  '租户';

-- 用户角色关联表
CREATE TABLE SYS_USER_ROLE(
  ID  VARCHAR2(32) NOT NULL,
  USER_ID  VARCHAR2(32),
  ROLE_ID  VARCHAR2(32),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_USER_ROLE PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_USER_ROLE IS '应用层-用户角色关联表';
 COMMENT ON COLUMN SYS_USER_ROLE.ID IS  '主键ID';
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS  '用户ID';
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS  '角色ID';
COMMENT ON COLUMN SYS_USER_ROLE.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_USER_ROLE.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_USER_ROLE.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_USER_ROLE.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_USER_ROLE.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_USER_ROLE.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_USER_ROLE.TENANT IS  '租户';

-- 角色部门关联表
CREATE TABLE SYS_ROLE_DEPT(
  ID  VARCHAR2(32) NOT NULL,
  ROLE_ID  VARCHAR2(32) NOT NULL,
  DEPT_ID  VARCHAR2(32) NOT NULL,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_ROLE_DEPT PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_ROLE_DEPT IS '应用层-角色部门关联表';
 COMMENT ON COLUMN SYS_ROLE_DEPT.ID IS  '依赖ID';
COMMENT ON COLUMN SYS_ROLE_DEPT.ROLE_ID IS  '角色ID';
COMMENT ON COLUMN SYS_ROLE_DEPT.DEPT_ID IS  '部门ID';
COMMENT ON COLUMN SYS_ROLE_DEPT.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_ROLE_DEPT.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_ROLE_DEPT.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_ROLE_DEPT.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_ROLE_DEPT.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_ROLE_DEPT.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_ROLE_DEPT.TENANT IS  '租户';

-- 系统菜单表
CREATE TABLE SYS_MENU(
  ID  VARCHAR2(32) NOT NULL,
  I_FRAME  CHAR(1),
  NAME  VARCHAR2(255),
  COMPONENT  VARCHAR2(255),
  PID  VARCHAR2(32),
  SORT  DECIMAL(19,0),
  ICON  VARCHAR2(255),
  PATH  VARCHAR2(255),
  CACHE  CHAR(1),
  HIDDEN  CHAR(1),
  COMPONENT_NAME  VARCHAR2(20),
  CREATE_TIME  DATE,
  PERMISSION  VARCHAR2(20),
  TYPE  DECIMAL(10,0),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_MENU PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_MENU IS '应用层-系统菜单表';
 COMMENT ON COLUMN SYS_MENU.ID IS  'ID';
COMMENT ON COLUMN SYS_MENU.I_FRAME IS  '是否外链';
COMMENT ON COLUMN SYS_MENU.NAME IS  '菜单名称';
COMMENT ON COLUMN SYS_MENU.COMPONENT IS  '组件';
COMMENT ON COLUMN SYS_MENU.PID IS  '上级菜单ID';
COMMENT ON COLUMN SYS_MENU.SORT IS  '排序';
COMMENT ON COLUMN SYS_MENU.ICON IS  '图标';
COMMENT ON COLUMN SYS_MENU.PATH IS  '链接地址';
COMMENT ON COLUMN SYS_MENU.CACHE IS  '缓存';
COMMENT ON COLUMN SYS_MENU.HIDDEN IS  '隐藏';
COMMENT ON COLUMN SYS_MENU.COMPONENT_NAME IS  '组件名称';
COMMENT ON COLUMN SYS_MENU.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN SYS_MENU.PERMISSION IS  '权限';
COMMENT ON COLUMN SYS_MENU.TYPE IS  '类型';
COMMENT ON COLUMN SYS_MENU.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN SYS_MENU.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_MENU.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN SYS_MENU.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN SYS_MENU.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_MENU.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN SYS_MENU.TENANT IS  '租户';

-- 对象菜单关联表
CREATE TABLE SYS_OBJECT_MENU(
  ID  VARCHAR2(32) NOT NULL,
  OBJECT_TYPE  VARCHAR2(32),
  OBJECT_ID  VARCHAR2(32),
  MENU_ID  VARCHAR2(32),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_OBJECT_MENU PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_OBJECT_MENU IS '应用层-对象菜单关联表';
 COMMENT ON COLUMN SYS_OBJECT_MENU.ID IS  '结果ID';
COMMENT ON COLUMN SYS_OBJECT_MENU.OBJECT_TYPE IS  '类型（dept-部门，role-角色，user-用户）';
COMMENT ON COLUMN SYS_OBJECT_MENU.OBJECT_ID IS  '对象ID';
COMMENT ON COLUMN SYS_OBJECT_MENU.MENU_ID IS  '菜单ID';
COMMENT ON COLUMN SYS_OBJECT_MENU.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_OBJECT_MENU.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_OBJECT_MENU.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_OBJECT_MENU.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_OBJECT_MENU.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_OBJECT_MENU.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_OBJECT_MENU.TENANT IS  '租户';

-- 数据字典表
CREATE TABLE SYS_DICT(
  ID  VARCHAR2(32) NOT NULL,
  DICT_NAME  VARCHAR2(100),
  NAME  VARCHAR2(32),
  DICT_CODE  VARCHAR2(100),
  REMARK  VARCHAR2(255),
  DESCRIPTION  VARCHAR2(255),
  DEL_FLAG  NUMBER(1),
  CREATE_BY  VARCHAR2(32),
  CREATE_TIME  DATE,
  UPDATE_BY  VARCHAR2(32),
  UPDATE_TIME  DATE,
  TYPE  NUMBER(1),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_DICT PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_DICT IS '应用层-数据字典表';
 COMMENT ON COLUMN SYS_DICT.ID IS  '主键ID';
COMMENT ON COLUMN SYS_DICT.DICT_NAME IS  '字典名称';
COMMENT ON COLUMN SYS_DICT.NAME IS  '字典名称';
COMMENT ON COLUMN SYS_DICT.DICT_CODE IS  '字典编码';
COMMENT ON COLUMN SYS_DICT.REMARK IS  '描述';
COMMENT ON COLUMN SYS_DICT.DESCRIPTION IS  '描述';
COMMENT ON COLUMN SYS_DICT.DEL_FLAG IS  '删除状态';
COMMENT ON COLUMN SYS_DICT.CREATE_BY IS  '创建人';
COMMENT ON COLUMN SYS_DICT.CREATE_TIME IS  '创建时间';
COMMENT ON COLUMN SYS_DICT.UPDATE_BY IS  '更新人';
COMMENT ON COLUMN SYS_DICT.UPDATE_TIME IS  '更新时间';
COMMENT ON COLUMN SYS_DICT.TYPE IS  '字典类型0为string,1为number';
COMMENT ON COLUMN SYS_DICT.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN SYS_DICT.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_DICT.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN SYS_DICT.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN SYS_DICT.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_DICT.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN SYS_DICT.TENANT IS  '租户';

-- 数据字典详情表
CREATE TABLE SYS_DICT_DETAIL(
  ID  VARCHAR2(32) NOT NULL,
  LABEL  VARCHAR2(255),
  VALUE  VARCHAR2(255),
  SORT  VARCHAR2(5),
  DICT_ID  VARCHAR2(32),
  CREATE_TIME  DATE,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_DICT_DETAIL PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_DICT_DETAIL IS '应用层-数据字典详情表';
 COMMENT ON COLUMN SYS_DICT_DETAIL.ID IS  '主键ID';
COMMENT ON COLUMN SYS_DICT_DETAIL.LABEL IS  '字典标签';
COMMENT ON COLUMN SYS_DICT_DETAIL.VALUE IS  '字典值';
COMMENT ON COLUMN SYS_DICT_DETAIL.SORT IS  '排序';
COMMENT ON COLUMN SYS_DICT_DETAIL.DICT_ID IS  '字典id';
COMMENT ON COLUMN SYS_DICT_DETAIL.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN SYS_DICT_DETAIL.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN SYS_DICT_DETAIL.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_DICT_DETAIL.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN SYS_DICT_DETAIL.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN SYS_DICT_DETAIL.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_DICT_DETAIL.UPD_DATE IS  '修改日期';
COMMENT ON COLUMN SYS_DICT_DETAIL.TENANT IS  '租户';

-- 岗位表
CREATE TABLE SYS_JOB(
  ID  VARCHAR2(32) NOT NULL,
  NAME  VARCHAR2(255),
  ENABLED  CHAR(1),
  SORT  DECIMAL(19,0),
  DEPT_ID  VARCHAR2(32),
  CREATE_TIME  DATE,
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_JOB PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_JOB IS '应用层-岗位表';
 COMMENT ON COLUMN SYS_JOB.ID IS  'ID';
COMMENT ON COLUMN SYS_JOB.NAME IS  '岗位名称';
COMMENT ON COLUMN SYS_JOB.ENABLED IS  '岗位状态';
COMMENT ON COLUMN SYS_JOB.SORT IS  '岗位排序';
COMMENT ON COLUMN SYS_JOB.DEPT_ID IS  '部门ID';
COMMENT ON COLUMN SYS_JOB.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN SYS_JOB.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_JOB.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_JOB.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_JOB.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_JOB.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_JOB.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_JOB.TENANT IS  '租户';

-- 系统日志表
CREATE TABLE SYS_LOG(
  ID  VARCHAR2(32) NOT NULL,
  CREATE_TIME  DATE,
  DESCRIPTION  VARCHAR2(255),
  EXCEPTION_DETAIL  CLOB,
  LOG_TYPE  VARCHAR2(255),
  METHOD  VARCHAR2(255),
  PARAMS  CLOB,
  REQUEST_IP  VARCHAR2(255),
  TIME  DECIMAL(19,0),
  USERNAME  VARCHAR2(255),
  ADDRESS  VARCHAR2(255),
  BROWSER  VARCHAR2(255),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_LOG PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_LOG IS '应用层-系统日志表';
 COMMENT ON COLUMN SYS_LOG.ID IS  '主键ID';
COMMENT ON COLUMN SYS_LOG.CREATE_TIME IS  '时间';
COMMENT ON COLUMN SYS_LOG.DESCRIPTION IS  '描述';
COMMENT ON COLUMN SYS_LOG.EXCEPTION_DETAIL IS  '异常';
COMMENT ON COLUMN SYS_LOG.LOG_TYPE IS  '类型';
COMMENT ON COLUMN SYS_LOG.METHOD IS  '方法';
COMMENT ON COLUMN SYS_LOG.PARAMS IS  '参数';
COMMENT ON COLUMN SYS_LOG.REQUEST_IP IS  'IP';
COMMENT ON COLUMN SYS_LOG.TIME IS  '耗时';
COMMENT ON COLUMN SYS_LOG.USERNAME IS  '用户';
COMMENT ON COLUMN SYS_LOG.ADDRESS IS  '地址';
COMMENT ON COLUMN SYS_LOG.BROWSER IS  '浏览器';
COMMENT ON COLUMN SYS_LOG.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_LOG.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_LOG.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_LOG.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_LOG.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_LOG.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_LOG.TENANT IS  '租户';

-- 角色菜单关联表
CREATE TABLE SYS_ROLE_MENU(
  ID  VARCHAR2(32) NOT NULL,
  MENU_ID  VARCHAR2(32),
  ROLE_ID  VARCHAR2(32),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_ROLE_MENU PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_ROLE_MENU IS '应用层-角色菜单关联表';
 COMMENT ON COLUMN SYS_ROLE_MENU.ID IS  '主键ID';
COMMENT ON COLUMN SYS_ROLE_MENU.MENU_ID IS  '菜单ID';
COMMENT ON COLUMN SYS_ROLE_MENU.ROLE_ID IS  '角色ID';
COMMENT ON COLUMN SYS_ROLE_MENU.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_ROLE_MENU.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_ROLE_MENU.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_ROLE_MENU.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_ROLE_MENU.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_ROLE_MENU.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_ROLE_MENU.TENANT IS  '租户';

-- 访客记录表
CREATE TABLE SYS_VISITS(
  ID  VARCHAR2(32) NOT NULL,
  CREATE_TIME  DATE,
  VISITS_DATE  VARCHAR2(255),
  IP_COUNTS  DECIMAL(19,0),
  PV_COUNTS  DECIMAL(19,0),
  WEEK_DAY  VARCHAR2(255),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_VISITS PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_VISITS IS '应用层-访客记录';
 COMMENT ON COLUMN SYS_VISITS.ID IS  '主键';
COMMENT ON COLUMN SYS_VISITS.CREATE_TIME IS  '创建时间';
COMMENT ON COLUMN SYS_VISITS.VISITS_DATE IS  '访问时间';
COMMENT ON COLUMN SYS_VISITS.IP_COUNTS IS  'IP数';
COMMENT ON COLUMN SYS_VISITS.PV_COUNTS IS  'PV数';
COMMENT ON COLUMN SYS_VISITS.WEEK_DAY IS  '周次';
COMMENT ON COLUMN SYS_VISITS.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_VISITS.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_VISITS.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_VISITS.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_VISITS.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_VISITS.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_VISITS.TENANT IS  '租户';

-- 代码生成器配置表
CREATE TABLE SYS_GEN_CONFIG(
  ID  VARCHAR2(32) NOT NULL,
  TABLE_NAME  VARCHAR2(255),
  AUTHOR  VARCHAR2(255),
  COVER  CHAR(1),
  MODULE_NAME  VARCHAR2(255),
  PACK  VARCHAR2(255),
  PATH  VARCHAR2(255),
  API_PATH  VARCHAR2(255),
  PREFIX  VARCHAR2(255),
  API_ALIAS  VARCHAR2(255),
  REMARK  VARCHAR2(255),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_GEN_CONFIG PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_GEN_CONFIG IS '应用层-代码生成器配置表';
 COMMENT ON COLUMN SYS_GEN_CONFIG.ID IS  'ID';
COMMENT ON COLUMN SYS_GEN_CONFIG.TABLE_NAME IS  '表名';
COMMENT ON COLUMN SYS_GEN_CONFIG.AUTHOR IS  '作者';
COMMENT ON COLUMN SYS_GEN_CONFIG.COVER IS  '是否覆盖';
COMMENT ON COLUMN SYS_GEN_CONFIG.MODULE_NAME IS  '模块名称';
COMMENT ON COLUMN SYS_GEN_CONFIG.PACK IS  '至于哪个包下';
COMMENT ON COLUMN SYS_GEN_CONFIG.PATH IS  '前端代码生成的路径';
COMMENT ON COLUMN SYS_GEN_CONFIG.API_PATH IS  '前端Api文件路径';
COMMENT ON COLUMN SYS_GEN_CONFIG.PREFIX IS  '表前缀';
COMMENT ON COLUMN SYS_GEN_CONFIG.API_ALIAS IS  '接口名称';
COMMENT ON COLUMN SYS_GEN_CONFIG.REMARK IS  '表描述';
COMMENT ON COLUMN SYS_GEN_CONFIG.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_GEN_CONFIG.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_GEN_CONFIG.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_GEN_CONFIG.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_GEN_CONFIG.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_GEN_CONFIG.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_GEN_CONFIG.TENANT IS  '租户';

-- 代码生成字段信息存储表
CREATE TABLE SYS_GEN_COLUMN_CONFIG(
  ID  VARCHAR2(32) NOT NULL,
  TABLE_NAME  VARCHAR2(255),
  COLUMN_NAME  VARCHAR2(255),
  COLUMN_TYPE  VARCHAR2(255),
  DICT_NAME  VARCHAR2(255),
  EXTRA  VARCHAR2(255),
  FORM_SHOW  CHAR(1),
  FORM_TYPE  VARCHAR2(255),
  KEY_TYPE  VARCHAR2(255),
  LIST_SHOW  CHAR(1),
  NOT_NULL  CHAR(1),
  QUERY_TYPE  VARCHAR2(255),
  REMARK  VARCHAR2(255),
  DATE_ANNOTATION  VARCHAR2(255),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_GEN_COLUMN_CONFIG PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_GEN_COLUMN_CONFIG IS '应用层-代码生成字段信息存储表';
 COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.ID IS  'ID';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.TABLE_NAME IS  '表名';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.COLUMN_NAME IS  '列名';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.COLUMN_TYPE IS  '列类型';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.DICT_NAME IS  '字典名';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.EXTRA IS  '';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.FORM_SHOW IS  '';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.FORM_TYPE IS  '';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.KEY_TYPE IS  '';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.LIST_SHOW IS  '';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.NOT_NULL IS  '';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.QUERY_TYPE IS  '查询类型';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.REMARK IS  '备注';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.DATE_ANNOTATION IS  '';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_GEN_COLUMN_CONFIG.TENANT IS  '租户';

-- 定时任务表
CREATE TABLE SYS_QUARTZ_JOB(
  ID  VARCHAR2(32) NOT NULL,
  BEAN_NAME  VARCHAR2(255),
  CRON_EXPRESSION  VARCHAR2(255),
  IS_PAUSE  CHAR(1),
  JOB_NAME  VARCHAR2(255),
  METHOD_NAME  VARCHAR2(255),
  PARAMS  VARCHAR2(255),
  REMARK  VARCHAR2(255),
  CREATE_TIME  DATE,
  DATE_ANNOTATION  VARCHAR2(255),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_QUARTZ_JOB PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_QUARTZ_JOB IS '应用层-定时任务表';
 COMMENT ON COLUMN SYS_QUARTZ_JOB.ID IS  'ID';
COMMENT ON COLUMN SYS_QUARTZ_JOB.BEAN_NAME IS  'Spring Bean名称';
COMMENT ON COLUMN SYS_QUARTZ_JOB.CRON_EXPRESSION IS  'cron 表达式';
COMMENT ON COLUMN SYS_QUARTZ_JOB.IS_PAUSE IS  '状态：1暂停、0启用';
COMMENT ON COLUMN SYS_QUARTZ_JOB.JOB_NAME IS  '任务名称';
COMMENT ON COLUMN SYS_QUARTZ_JOB.METHOD_NAME IS  '方法名称';
COMMENT ON COLUMN SYS_QUARTZ_JOB.PARAMS IS  '参数';
COMMENT ON COLUMN SYS_QUARTZ_JOB.REMARK IS  '备注';
COMMENT ON COLUMN SYS_QUARTZ_JOB.CREATE_TIME IS  '创建日期';
COMMENT ON COLUMN SYS_QUARTZ_JOB.DATE_ANNOTATION IS  '';
COMMENT ON COLUMN SYS_QUARTZ_JOB.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_QUARTZ_JOB.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_QUARTZ_JOB.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_QUARTZ_JOB.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_QUARTZ_JOB.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_QUARTZ_JOB.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_QUARTZ_JOB.TENANT IS  '租户';

-- 定时任务日志表
CREATE TABLE SYS_QUARTZ_LOG(
  ID  VARCHAR2(32) NOT NULL,
  BAEN_NAME  VARCHAR2(255),
  CREATE_TIME  DATE,
  CRON_EXPRESSION  VARCHAR2(255),
  EXCEPTION_DETAIL  CLOB,
  IS_SUCCESS  CHAR(1),
  JOB_NAME  VARCHAR2(255),
  METHOD_NAME  VARCHAR2(255),
  PARAMS  VARCHAR2(255),
  TIME  DECIMAL(19,0),
  CRT_USER_CODE  VARCHAR2(32),
  CRT_ORG_CODE  VARCHAR2(32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2(32),
  UPD_ORG_CODE  VARCHAR2(32),
  UPD_DATE  DATE,
  TENANT  VARCHAR2(32),
CONSTRAINT SYS_QUARTZ_LOG PRIMARY KEY (ID)
);
 COMMENT ON TABLE SYS_QUARTZ_LOG IS '应用层-定时任务日志表';
 COMMENT ON COLUMN SYS_QUARTZ_LOG.ID IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.BAEN_NAME IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.CREATE_TIME IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.CRON_EXPRESSION IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.EXCEPTION_DETAIL IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.IS_SUCCESS IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.JOB_NAME IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.METHOD_NAME IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.PARAMS IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.TIME IS  '';
COMMENT ON COLUMN SYS_QUARTZ_LOG.CRT_USER_CODE IS  '创建用户';
COMMENT ON COLUMN SYS_QUARTZ_LOG.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN SYS_QUARTZ_LOG.CRT_DATE IS  '创建时间';
COMMENT ON COLUMN SYS_QUARTZ_LOG.UPD_USER_CODE IS  '修改用户';
COMMENT ON COLUMN SYS_QUARTZ_LOG.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN SYS_QUARTZ_LOG.UPD_DATE IS  '修改时间';
COMMENT ON COLUMN SYS_QUARTZ_LOG.TENANT IS  '租户';


