#配置数据源
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          driverClassName: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
          username: pncs
          password: pncs
        smartbi:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:6688/smartbidemo
          username: admin
          password: admin
      druid:
      #      driverClassName: oracle.jdbc.driver.OracleDriver
      #      url: jdbc:oracle:thin:@11.1.100.2:1521:orcl
      #      username: eladmin_base
      #      password: eladmin_base
        # 初始化配置
        initial-size: 3
        # 最小连接数
        min-idle: 3
        # 最大连接数
        max-active: 15
        # 获取连接超时时间
        max-wait: 5000
        # 连接有效性检测时间
        time-between-eviction-runs-millis: 90000
        # 最大空闲时间
        min-evictable-idle-time-millis: 1800000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false

        validation-query: select 1 from dual
        # 配置监控统计拦截的filters
        filters: stat
        stat-view-servlet:
          url-pattern: /druid/*
          reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

#sso
sso:
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: YTFiMmMzZDRlNWY2ZzdoOGk5ajEwazExbDEybTEzbjE0bzE1cDE2cTE3cjE4czE5dDIwdTIxdjIydzIzeDI0eTI1ejI2YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
  #ticket 过期时间 90秒
  expiration: 90000
  key: sso-key
smartbi:
  url: http://localhost:18080/smartbi
  username: admin
  password: admin
#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true
  print-init: true
  security-configuration:
    client-id: client-1
    client-secret: secretA
    scope-separator: \,
    use-basic-authentication-with-access-code-grant: true
  dockets:
    docket-core:
      base-package: com.pactera.core
      group-name: 公共部分-CORE
    docket-indicator:
      base-package: com.pactera.indicator
      group-name: 指标平台-INDICATOR

# 文件存储路径
file:
  path: D:\eladmin-files\file\
  image: D:\eladmin-files\image\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

# 详细日志/包括SQL/参数
logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace